[graph]
all-features = true

[advisories]
unmaintained = "all"
yanked = "deny"
ignore = []

[licenses]
confidence-threshold = 0.93
allow = ["AGPL-3.0-or-later", "MIT", "Apache-2.0", "BSD-3-Clause", "Unicode-3.0", "BlueOak-1.0.0", "Zlib"]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
