[package]
name = "nulllobby-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[[bin]]
name = "nulllobby"
path = "src/main.rs"

[dependencies]
nulllobby-core.workspace = true
nulllobby-platform.workspace = true

[lints]
workspace = true
