[package]
name = "nulllobby-direct"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
getrandom.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["net", "rt", "macros", "time"] }
nulllobby-transport.workspace = true
bendy = "0.6.1"

[lints]
workspace = true
